### Preperation ####
# replace <HEAD-SERIAL-HERE> with the serial number of your second battery

alias: zendure_custom_ACMode
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_select.acmode
    for:
      hours: 0
      minutes: 0
      seconds: 0
conditions: []
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: "2"
      retain: false
      payload: "{{ states.input_select.acmode.state }}"
      topic: Zendure/select/<HEAD-SERIAL-HERE>/acMode/set
mode: single
